### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by nicklaw5** [techpines/bone.io#29]
I have just come across this library and wanted to know if it is still being maintained?

**Comment by kublermdk** [comment]
I suggest checking out Meteor.js it's what I changed to after having a play
with this. But then it depends on your love of MongoDB and other
requirements.

## 

Michael Kubler
Mob : 0433483008
"Change is not a spectator sport"

**Comment by nicklaw5** [comment]
Ok thanks. Don't think Meteor is for me though.
