### ISSUE TITLE
Start up on the documentation

### ISSUE THREAD

**Issue by techpines** [techpines/bone.io#3]
We need to start writing some documentation for this bad boy.

To edit the docs, make changes to `README.md`.

If you need examples of how the readme syntax works look here:

This is what it renders like:
https://github.com/techpines/express.io/blob/master/README.md

Here is what the code looks like:
https://raw.github.com/techpines/express.io/master/README.md

As a first pass it would be nice to document the `views`, `logger`, and `io` parts of the lib.

**Comment by BenjaminAdams** [comment]
I feel I did a bad job at naming things, but it's a start at least

**Comment by techpines** [comment]
I think that's a good start.
