### ISSUE TITLE
Build system for bone.io.js and bone.io.min.js

### ISSUE THREAD

**Issue by techpines** [techpines/bone.io#5]
We need a build system to generate the javascript files in the top level directory of the project from the index.coffee file.

I'd like to use grunt, http://gruntjs.com/

Basically, in the top-level directory of the project.  We want to get two files:

```
/bone.io.js
/bone.io.min.js
```

**Comment by techpines** [comment]
Also, if grunt doesn't look like a good solution.  I am open to anything else.

**Comment by BenjaminAdams** [comment]
do npm install 
then type grunt in the command line

https://github.com/techpines-co/bone.io/commit/076ad24d07f6a2ef4c488254b5f61ef6a0e14569
